#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/colourdata.h>
#include <wx/colordlg.h>

class Matrix4;
class Vector4;

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	public:
		GUIMyFrame1( wxWindow* parent );
		void Repaint();

	protected:
		void WxPanel_Repaint( wxUpdateUIEvent& event );
		void m_button_load_geometry_click( wxCommandEvent& event );
		void Scrolls_Updated(wxScrollEvent& event);
		void ScrollX_Updated(wxScrollEvent& event);
		void ScrollY_Updated(wxScrollEvent& event);
		void ScrollZ_Updated(wxScrollEvent& event);
		void update_labels();

	private:
		bool draw = true;
		Matrix4 getRotationMatrix();
		Matrix4 getScaleMatrix();
		Matrix4 getTranslationMatrix();
		Matrix4 getCenterMatrix();
};

#endif // __GUIMyFrame1__
